import { LookupOption } from '../core/models';

export interface SkillGroupDefinition {
  label: string;
  aliases: readonly string[];
  skills?: readonly string[];
}

export interface SkillGroupTab {
  label: string;
  count: number;
}

export const DEFAULT_SKILL_GROUP_LABEL = 'Software Engineer / Backend Engineer';

export const SKILL_GROUP_DEFINITIONS: readonly SkillGroupDefinition[] = [
  {
    label: 'Software Engineer / Backend Engineer',
    aliases: ['Software Engineer / Backend Engineer', 'Backend', 'Database'],
    skills: [
      'Java',
      'Spring Boot',
      'Hibernate',
      'JPA',
      'REST APIs',
      'Microservices',
      'Node.js',
      'Express.js',
      'NestJS',
      'Python',
      'Django',
      'Flask',
      'FastAPI',
      'C#',
      '.NET',
      '.NET Core',
      'ASP.NET',
      'PHP',
      'Laravel',
      'Ruby on Rails',
      'Go',
      'Kotlin',
      'Scala',
      'SQL',
      'SQL Server',
      'PostgreSQL',
      'MySQL',
      'MongoDB',
      'Redis',
      'Kafka',
      'RabbitMQ',
      'Elasticsearch',
      'GraphQL',
      'Docker',
      'Kubernetes',
      'AWS',
      'Azure',
      'GCP',
      'Git',
      'CI/CD',
      'Unit Testing',
      'System Design',
      'API Design',
      'Design Patterns',
      'Clean Architecture',
    ],
  },
  {
    label: 'Frontend Engineer',
    aliases: ['Frontend Engineer', 'Frontend'],
    skills: [
      'JavaScript',
      'TypeScript',
      'React',
      'React.js',
      'Next.js',
      'Angular',
      'Vue.js',
      'Nuxt.js',
      'HTML',
      'CSS',
      'SCSS',
      'Tailwind CSS',
      'Bootstrap',
      'Redux',
      'Zustand',
      'React Query',
      'Webpack',
      'Vite',
      'Material UI',
      'Ant Design',
      'Responsive Design',
      'Cross-Browser Compatibility',
      'REST API Integration',
      'GraphQL',
      'Jest',
      'Cypress',
      'Playwright',
      'Figma to HTML',
      'Accessibility',
      'Web Performance Optimization',
    ],
  },
  {
    label: 'Full Stack Engineer',
    aliases: ['Full Stack Engineer', 'Full Stack'],
    skills: [
      'JavaScript',
      'TypeScript',
      'React',
      'React.js',
      'Next.js',
      'Angular',
      'Vue.js',
      'Node.js',
      'Express.js',
      'NestJS',
      'Java',
      'Spring Boot',
      'Python',
      'Django',
      'Flask',
      '.NET Core',
      'REST APIs',
      'GraphQL',
      'PostgreSQL',
      'MySQL',
      'MongoDB',
      'Redis',
      'Docker',
      'Kubernetes',
      'AWS',
      'Azure',
      'Firebase',
      'Supabase',
      'CI/CD',
      'Git',
      'Authentication',
      'Authorization',
      'OAuth',
      'JWT',
      'Microservices',
      'System Design',
    ],
  },
  {
    label: 'Mobile App Developer',
    aliases: ['Mobile App Developer', 'Mobile'],
    skills: [
      'Android',
      'Kotlin',
      'Java',
      'iOS',
      'Swift',
      'SwiftUI',
      'Objective-C',
      'Flutter',
      'Dart',
      'React Native',
      'Expo',
      'Firebase',
      'REST APIs',
      'GraphQL',
      'SQLite',
      'Realm',
      'Push Notifications',
      'App Store Deployment',
      'Play Store Deployment',
      'Mobile UI/UX',
      'Offline Storage',
      'In-App Purchases',
      'Maps Integration',
      'Crashlytics',
      'Mobile Performance Optimization',
    ],
  },
  {
    label: 'Data Scientist',
    aliases: ['Data Scientist', 'Data'],
    skills: [
      'Python',
      'R',
      'SQL',
      'Pandas',
      'NumPy',
      'Scikit-learn',
      'TensorFlow',
      'PyTorch',
      'Keras',
      'Machine Learning',
      'Deep Learning',
      'NLP',
      'Computer Vision',
      'Statistical Modeling',
      'Predictive Modeling',
      'Feature Engineering',
      'Data Cleaning',
      'Data Visualization',
      'Matplotlib',
      'Seaborn',
      'Plotly',
      'Jupyter Notebook',
      'A/B Testing',
      'Hypothesis Testing',
      'Regression',
      'Classification',
      'Clustering',
      'Time Series Forecasting',
      'Model Evaluation',
      'MLOps',
      'MLflow',
    ],
  },
  {
    label: 'Data Engineer',
    aliases: ['Data Engineer'],
    skills: [
      'Python',
      'SQL',
      'Spark',
      'PySpark',
      'Hadoop',
      'Airflow',
      'Kafka',
      'dbt',
      'ETL',
      'ELT',
      'Data Warehousing',
      'Data Lakes',
      'Snowflake',
      'BigQuery',
      'Redshift',
      'Azure Data Factory',
      'AWS Glue',
      'Databricks',
      'PostgreSQL',
      'MySQL',
      'MongoDB',
      'NoSQL',
      'Data Modeling',
      'Data Pipelines',
      'Batch Processing',
      'Stream Processing',
      'Data Quality',
      'Data Governance',
    ],
  },
  {
    label: 'AI / Machine Learning Engineer',
    aliases: ['AI / Machine Learning Engineer', 'AI/ML', 'Machine Learning Engineer'],
    skills: [
      'Python',
      'Machine Learning',
      'Deep Learning',
      'TensorFlow',
      'PyTorch',
      'Scikit-learn',
      'NLP',
      'Computer Vision',
      'Transformers',
      'LLMs',
      'LangChain',
      'LlamaIndex',
      'OpenAI API',
      'Hugging Face',
      'Vector Databases',
      'Pinecone',
      'Weaviate',
      'FAISS',
      'ChromaDB',
      'Embeddings',
      'RAG',
      'Prompt Engineering',
      'Model Fine-tuning',
      'Model Deployment',
      'MLflow',
      'Docker',
      'Kubernetes',
      'FastAPI',
      'MLOps',
    ],
  },
  {
    label: 'DevOps Engineer',
    aliases: ['DevOps Engineer', 'DevOps'],
    skills: [
      'Linux',
      'Shell Scripting',
      'Docker',
      'Kubernetes',
      'Helm',
      'Terraform',
      'Ansible',
      'Jenkins',
      'GitHub Actions',
      'GitLab CI/CD',
      'Azure DevOps',
      'AWS',
      'Azure',
      'GCP',
      'Nginx',
      'Apache',
      'Load Balancing',
      'Monitoring',
      'Prometheus',
      'Grafana',
      'ELK Stack',
      'CloudWatch',
      'Infrastructure as Code',
      'CI/CD Pipelines',
      'Networking',
      'Security',
      'SSL',
      'DNS',
      'Autoscaling',
      'Serverless',
      'Bash',
      'Python',
    ],
  },
  {
    label: 'QA Engineer / SQA',
    aliases: ['QA Engineer / SQA', 'QA', 'SQA'],
    skills: [
      'Manual Testing',
      'Automation Testing',
      'Selenium',
      'Cypress',
      'Playwright',
      'Appium',
      'Postman',
      'API Testing',
      'Regression Testing',
      'Smoke Testing',
      'Sanity Testing',
      'Functional Testing',
      'Non-Functional Testing',
      'Performance Testing',
      'JMeter',
      'Load Testing',
      'Security Testing',
      'Test Cases',
      'Test Plans',
      'Bug Reporting',
      'Jira',
      'TestRail',
      'Agile Testing',
      'Mobile Testing',
      'Web Testing',
      'Database Testing',
      'SQL',
    ],
  },
  {
    label: 'UI/UX Designer',
    aliases: ['UI/UX Designer', 'Design'],
    skills: [
      'Figma',
      'Adobe XD',
      'Sketch',
      'Wireframing',
      'Prototyping',
      'User Research',
      'User Flows',
      'Information Architecture',
      'Design Systems',
      'UI Design',
      'UX Design',
      'Interaction Design',
      'Responsive Design',
      'Mobile App Design',
      'Web App Design',
      'Usability Testing',
      'Accessibility',
      'Journey Mapping',
      'Persona Creation',
      'Visual Design',
      'Typography',
      'Color Theory',
      'Design Handoff',
    ],
  },
  {
    label: 'Product Manager',
    aliases: ['Product Manager'],
    skills: [
      'Product Strategy',
      'Roadmap Planning',
      'Requirement Gathering',
      'User Stories',
      'PRD Writing',
      'Agile',
      'Scrum',
      'Kanban',
      'Stakeholder Management',
      'Market Research',
      'Competitor Analysis',
      'Product Discovery',
      'MVP Planning',
      'Backlog Management',
      'Prioritization',
      'Jira',
      'Confluence',
      'Analytics',
      'A/B Testing',
      'User Research',
      'Customer Interviews',
      'Go-to-Market Strategy',
    ],
  },
  {
    label: 'Project Manager / Scrum Master',
    aliases: ['Project Manager / Scrum Master', 'Project Manager', 'Scrum Master'],
    skills: [
      'Project Planning',
      'Agile',
      'Scrum',
      'Kanban',
      'Sprint Planning',
      'Daily Standups',
      'Risk Management',
      'Resource Management',
      'Timeline Management',
      'Budget Management',
      'Stakeholder Communication',
      'Jira',
      'Trello',
      'Asana',
      'MS Project',
      'Confluence',
      'Team Coordination',
      'Reporting',
      'Dependency Management',
      'Conflict Resolution',
      'Delivery Management',
      'Change Management',
    ],
  },
  {
    label: 'Business Analyst',
    aliases: ['Business Analyst'],
    skills: [
      'Requirement Gathering',
      'Requirement Documentation',
      'BRD',
      'FRD',
      'User Stories',
      'Use Cases',
      'Process Mapping',
      'Gap Analysis',
      'Stakeholder Interviews',
      'Wireframes',
      'Data Analysis',
      'SQL',
      'Excel',
      'Power BI',
      'Jira',
      'Confluence',
      'Agile',
      'Scrum',
      'Acceptance Criteria',
      'UAT',
      'Business Process Modeling',
      'Workflow Analysis',
      'Documentation',
    ],
  },
  {
    label: 'HR / Recruiter',
    aliases: ['HR / Recruiter', 'HR', 'Recruitment'],
    skills: [
      'Talent Acquisition',
      'Technical Recruitment',
      'Non-Technical Recruitment',
      'Candidate Screening',
      'Interview Scheduling',
      'Job Posting',
      'Job Description Writing',
      'LinkedIn Recruiter',
      'Boolean Search',
      'Applicant Tracking Systems',
      'Resume Screening',
      'Sourcing',
      'Onboarding',
      'Employee Engagement',
      'HR Operations',
      'Payroll Coordination',
      'Performance Management',
      'HR Policies',
      'Offer Management',
      'Employee Relations',
      'Background Verification',
    ],
  },
  {
    label: 'Sales / Business Development',
    aliases: ['Sales / Business Development', 'Sales'],
    skills: [
      'Lead Generation',
      'B2B Sales',
      'B2C Sales',
      'Cold Calling',
      'Cold Emailing',
      'LinkedIn Prospecting',
      'CRM',
      'HubSpot',
      'Salesforce',
      'Zoho CRM',
      'Pipeline Management',
      'Client Communication',
      'Proposal Writing',
      'Negotiation',
      'Closing Deals',
      'Account Management',
      'Market Research',
      'Sales Strategy',
      'Upselling',
      'Cross-Selling',
      'Customer Relationship Management',
      'Presentation Skills',
      'Demo Calls',
    ],
  },
  {
    label: 'Marketing',
    aliases: ['Marketing'],
    skills: [
      'Digital Marketing',
      'SEO',
      'SEM',
      'Google Ads',
      'Meta Ads',
      'LinkedIn Ads',
      'Content Marketing',
      'Email Marketing',
      'Social Media Marketing',
      'Marketing Strategy',
      'Campaign Management',
      'Google Analytics',
      'Keyword Research',
      'Copywriting',
      'Branding',
      'Lead Generation',
      'HubSpot',
      'Mailchimp',
      'Marketing Automation',
      'Conversion Optimization',
      'A/B Testing',
      'Influencer Marketing',
    ],
  },
  {
    label: 'Finance / Accounts',
    aliases: ['Finance / Accounts', 'Finance'],
    skills: [
      'Accounting',
      'Bookkeeping',
      'QuickBooks',
      'Xero',
      'Excel',
      'Financial Reporting',
      'Budgeting',
      'Forecasting',
      'Payroll',
      'Taxation',
      'Auditing',
      'Accounts Payable',
      'Accounts Receivable',
      'Bank Reconciliation',
      'Financial Analysis',
      'ERP',
      'SAP',
      'Oracle Financials',
      'Compliance',
      'Invoicing',
      'Expense Management',
    ],
  },
  {
    label: 'Customer Support / Customer Success',
    aliases: ['Customer Support / Customer Success', 'Customer Support'],
    skills: [
      'Customer Support',
      'Customer Success',
      'Ticket Management',
      'Zendesk',
      'Freshdesk',
      'Intercom',
      'Live Chat',
      'Email Support',
      'Phone Support',
      'CRM',
      'Client Onboarding',
      'Product Training',
      'Issue Resolution',
      'Escalation Management',
      'Customer Retention',
      'Customer Satisfaction',
      'SLA Management',
      'Communication Skills',
      'Troubleshooting',
    ],
  },
  {
    label: 'Cybersecurity Engineer',
    aliases: ['Cybersecurity Engineer', 'Security'],
    skills: [
      'Network Security',
      'Application Security',
      'Cloud Security',
      'Penetration Testing',
      'Vulnerability Assessment',
      'SIEM',
      'SOC',
      'IDS',
      'IPS',
      'Firewalls',
      'OWASP',
      'Ethical Hacking',
      'Burp Suite',
      'Kali Linux',
      'Nmap',
      'Wireshark',
      'IAM',
      'Zero Trust',
      'Security Audits',
      'Incident Response',
      'Threat Modeling',
      'Compliance',
      'ISO 27001',
      'SOC 2',
      'GDPR',
    ],
  },
  {
    label: 'Cloud Engineer',
    aliases: ['Cloud Engineer', 'Cloud'],
    skills: [
      'AWS',
      'Azure',
      'GCP',
      'EC2',
      'S3',
      'Lambda',
      'RDS',
      'CloudFront',
      'IAM',
      'VPC',
      'Azure Functions',
      'Azure App Service',
      'AKS',
      'GKE',
      'Cloud Run',
      'Terraform',
      'CloudFormation',
      'Kubernetes',
      'Docker',
      'Serverless',
      'Monitoring',
      'Cost Optimization',
      'Cloud Security',
      'Networking',
      'Load Balancing',
      'Autoscaling',
      'Disaster Recovery',
    ],
  },
];

const SKILL_GROUP_NAME_LOOKUP = new Map(
  SKILL_GROUP_DEFINITIONS.map((group) => [
    group.label,
    new Set((group.skills ?? []).map((skill) => normalizeSkillText(skill))),
  ]),
);

export function normalizeSkillText(value: string): string {
  return value.trim().toLowerCase();
}

export function buildSkillGroupTabs(skills: readonly LookupOption[]): SkillGroupTab[] {
  return SKILL_GROUP_DEFINITIONS.map((group) => ({
    label: group.label,
    count: skillsForGroup(skills, group.label).length,
  })).filter((group) => group.count > 0);
}

export function selectedSkillOptionsFor(
  skills: readonly LookupOption[],
  selectedSkillIds: readonly string[],
): LookupOption[] {
  const selected = new Set(selectedSkillIds);
  return skills.filter((skill) => selected.has(skill.id));
}

export function visibleSkillsForPicker(
  skills: readonly LookupOption[],
  query: string,
  activeGroup: string,
): LookupOption[] {
  const normalizedQuery = query.trim().toLowerCase();
  if (normalizedQuery) {
    return skills.filter((skill) =>
      `${skill.name} ${skill.description ?? ''}`.toLowerCase().includes(normalizedQuery),
    );
  }

  const tabs = buildSkillGroupTabs(skills);
  const resolvedGroup = tabs.some((group) => group.label === activeGroup)
    ? activeGroup
    : tabs[0]?.label;

  return resolvedGroup ? skillsForGroup(skills, resolvedGroup) : [...skills];
}

export function skillsForGroup(skills: readonly LookupOption[], groupLabel: string): LookupOption[] {
  const group = SKILL_GROUP_DEFINITIONS.find((item) => item.label === groupLabel);
  if (!group) {
    return [];
  }

  const groupNames = SKILL_GROUP_NAME_LOOKUP.get(group.label) ?? new Set<string>();
  const aliases = new Set(group.aliases.map((alias) => normalizeSkillText(alias)));

  return skills.filter((skill) => {
    const nameMatch = groupNames.has(normalizeSkillText(skill.name));
    const categoryMatch = skill.description ? aliases.has(normalizeSkillText(skill.description)) : false;
    return nameMatch || categoryMatch;
  });
}

export function visibleSkillGroupTitle(query: string, activeGroup: string): string {
  return query.trim() ? 'Search results' : activeGroup;
}

export function visibleSkillGroupSubtitle(query: string, visibleCount: number): string {
  return query.trim()
    ? `${visibleCount} matching skill(s) across all groups.`
    : `${visibleCount} skill(s) in this role family.`;
}

export function toggleSkillId(
  selectedSkillIds: readonly string[],
  skillId: string,
  selected: boolean,
): string[] {
  if (selected) {
    return selectedSkillIds.includes(skillId)
      ? [...selectedSkillIds]
      : [...selectedSkillIds, skillId];
  }

  return selectedSkillIds.filter((id) => id !== skillId);
}
